### ISSUE TITLE
Error when running colab demo

### ISSUE THREAD

**Issue by sshhaawwnn111** [modelscope/facechain#309]
```
Traceback (most recent call last):
  File "/content/facechain/facechain/train_text_to_image_lora.py", line 1161, in <module>
    main()
  File "/content/facechain/facechain/train_text_to_image_lora.py", line 785, in main
    raise ValueError(
ValueError: --caption_column' value 'text' needs to be one of: image
```

Always get this error message when training on colab demo. Thank you.

**Comment by sunbaigui** [comment]
> ```
> Traceback (most recent call last):
>   File "/content/facechain/facechain/train_text_to_image_lora.py", line 1161, in <module>
>     main()
>   File "/content/facechain/facechain/train_text_to_image_lora.py", line 785, in main
>     raise ValueError(
> ValueError: --caption_column' value 'text' needs to be one of: image
> ```
> 
> Always get this error message when training on colab demo. Thank you.

please refer to #171 ，see if it can solve your problem.

**Comment by sshhaawwnn111** [comment]
Seems like he solved it by adjusting the version of datasets, which I have already tried (he didn't specify what version). 

I tried to remove the try-except and got another error:
```
Traceback (most recent call last):
  File "/content/facechain/facechain/train_text_to_image_lora.py", line 1161, in <module>
    main()
  File "/content/facechain/facechain/train_text_to_image_lora.py", line 748, in main
    dataset = load_dataset(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1773, in load_dataset
    builder_instance = load_dataset_builder(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1502, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1221, in dataset_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a dataset script at /tmp/qw/training_data/ly261666/cv_portrait_model/demo1_labeled/demo1_labeled.py or any data file in the same directory.
```

**Comment by 68a** [comment]
File "/content/facechain/facechain/train_text_to_image_lora.py", line 193, in prepare_dataset
    image = get_rot(image)
  File "/content/facechain/facechain/train_text_to_image_lora.py", line 144, in get_rot
    ort_session = onnxruntime.InferenceSession(model_path)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 432, in __init__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by DestoryVIP** [comment]
> File "/content/facechain/facechain/train_text_to_image_lora.py", line 193, in prepare_dataset image = get_rot(image) File "/content/facechain/facechain/train_text_to_image_lora.py", line 144, in get_rot ort_session = onnxruntime.InferenceSession(model_path) File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 432, in **init** raise e File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in **init** self._create_inference_session(providers, provider_options, disabled_optimizers) File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session raise ValueError( ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

![image](https://github.com/modelscope/facechain/assets/39025726/12c99e12-0510-4d62-9fd1-d55fcefcce4c)

for this ,you can fix up this mistake for following :
ort_session = onnxruntime.InferenceSession(model_path,providers=onnxruntime.get_all_providers())

**Comment by Husky110** [comment]
Okay - I seem to have found the problem causing the main issue. I had the same error as @sshhaawwnn111 when running the colab-workbook on a free tier. Since google blocked running stable-diffusion with a webui the solution is pretty simple:
1.) Don't be a cheap bastard in Google's eyes and buy some calculation units (or whatever they are called in english) and use a runtime with "A100". 
2.) install the collab-workbook
3.) run `!pip install onnxruntime==1.15.1` to avoid issue #319 
4.) replace line 144 in facechain/train_text_to_image_lora with the fix by @DestoryVIP `ort_session = onnxruntime.InferenceSession(model_path,providers=onnxruntime.get_all_providers())`
5.) When you run the workbook the first time, it will fail with "context already set". Don't be disencouraged - just run `!python3 app.py` manually and it will work then.
6.) Profit!

So the main problem is googles ban on sd with a web-ui. See here for more info: https://decrypt.co/197428/google-colab-stable-diffusion-web-ui-ban

**Comment by sshhaawwnn111** [comment]
@Husky110 thanks for the detailed reply!!
