### ISSUE TITLE
Runtime error in Huggingface space

### ISSUE THREAD

**Issue by maharshi-p** [modelscope/facechain#560]
I am trying to use HF space for trying out facechain-FACT but the space has resulted in runtime error. Can you please look into it?

space link: https://huggingface.co/spaces/modelscope/FaceChain-FACT

<img width="815" alt="image" src="https://github.com/modelscope/facechain/assets/167762490/3c9cd033-848c-4b18-8aab-33ccfbdc3074">

**Comment by sunbaigui** [comment]
@You-Cun please check this out.

**Comment by You-Cun** [comment]
Thanks for your helpful comment. The runtime error sometimes happens because of model downloading timeout caused by network instability when waking up the space. You can try FaceChain-FACT on the more stable ModelScope Studio (https://www.modelscope.cn/studios/CVstudio/FaceChain-FACT). In addition, we will update our Huggingface space to avoid downloading when waking up the space soon.

**Comment by You-Cun** [comment]
We now update the Huggingface space and download all models in the environment building process. As such, it only takes about 3 minutes to wake up the space when it is sleeping.

**Comment by maharshi-p** [comment]
thank you so much for the help! Closing this issue 💯
