### ISSUE TITLE
Is the support for SDXL removed on the latest master branch?

### ISSUE THREAD

**Issue by mountlin** [modelscope/facechain#562]
I saw that SDXL support was merged in <https://github.com/modelscope/facechain/pull/436>, which is great. But it seems to be removed in <https://github.com/modelscope/facechain/pull/554>. 
I want to know whether the latest main branch still supports SDXL and XL models as base models? If it is indeed removed, will it be added in the future?

**Comment by sunbaigui** [comment]
> I saw that SDXL support was merged in #436, which is great. But it seems to be removed in #554. I want to know whether the latest main branch still supports SDXL and XL models as base models? If it is indeed removed, will it be added in the future?

we'll try our best to support both SDXL&SD3 as base models in the future.

**Comment by sh4wn** [comment]
> > I saw that SDXL support was merged in #436, which is great. But it seems to be removed in #554. I want to know whether the latest main branch still supports SDXL and XL models as base models? If it is indeed removed, will it be added in the future?
> 
> we'll try our best to support both SDXL&SD3 as base models in the future.

Is there any update?

**Comment by sunbaigui** [comment]
@sh4wn At present, we are investing in the development of full-body digital humans, and in about a month, we will have an IJCV work on 3D mesh full-body digital humans that will be integrated and released as open source. Due to a shortage of manpower and computing power, the current base model adaptation plan has been shelved, and we sincerely apologize for this.
